### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by LovelyA72** [frqnny/mostructures#56]
1.18 is out. I tried to run my server without this mod but the server just litters the console complaining about invalid structures and eventually stop responding and crash.

**Comment by frqnny** [comment]
ik not updating for month at least sorry

**Comment by filips123** [comment]
I know you said you first want to finish 1.3.0 on 1.17 and wait until Mojang finalizes the structures system in the future 1.18.x release, but I still decided to port the mod to 1.18 myself.

I haven't created a PR yet (because there is currently no 1.18.x branch I could use as a base branch), but the code is available [in my fork](https://github.com/filips123/mostructures/tree/1.18.x). I can open PR if you think that would be useful, but otherwise I'll just leave it there in case someone wants to try it or is needed in the future.

The code seems to work fine and all structures are generating. But it probably still needs some cleanup and testing if all features are working as they should.

**Comment by frqnny** [comment]
thanks but i thought biome api was broken

**Comment by frqnny** [comment]
thanks but i thought biome api was broken

**Comment by frqnny** [comment]
thanks but i thought biome api was broken

**Comment by frqnny** [comment]
thanks but i thought biome api was broken

**Comment by frqnny** [comment]
thanks but i thought biome api was broken

**Comment by filips123** [comment]
It seems most of the biome API was recently fixed in FabricMC/fabric#1834 (0.42.4+1.18). Anyways, should I create a PR for this?

**Comment by LovelyA72** [comment]
@filips123 I cloned your repository. Seems like it's for pre-1 and it can not run on the 1.18 release version?

**Comment by LovelyA72** [comment]
Or at least @frqnny please give me a way to remove every mostructures' data from my world so I can upgrade to 1.18

**Comment by filips123** [comment]
That `pre1` in the mod filename is part of the mod version (1.3.0-pre1). It should work on stable 1.18 Minecraft release.
