### ISSUE TITLE
End Volcanic Vent (Bug)

### ISSUE THREAD

**Issue by LeSalux** [frqnny/mostructures#57]
In the End Dimension Volcanic Vents are spawning, often over the void. This seems like a bug. This is in v1.3.0-pre1+1.18

**Comment by bessiq** [comment]
Having the same issue. Oddly, if you do `/locate mostructures:volcanic_vent` in The End, it says it can't find any nearby. But they are there, evenly spaced apart all along y 0. Doing the same locate command in the Overworld works though.

Not really hurting anything, but I guess it looks a bit odd! And the endermen seem to love it, which is weird since it spouts water. 🤷‍♂️

**Comment by AlexTheSuprWolf** [comment]
Having the same issue as well. Interestingly, while the /locate command doesn't work, the Explorer's Compass from the Explorer's Compass mod had no trouble pointing to them.

**Comment by Nova-Katt** [comment]
Same issue here, and it became quite the issue yesterday when we were building an endermen xp farm in the void, because the endermen kept spawning on the volcanic vents, making the xp farm inefficient, so we had to traverse the void A LOT in order to mine away like 10-15 volcanic vents, and then mine away our void bridges, just to get the farm working. xD

**Comment by theDerxu** [comment]
yeah please fix this, It is really annoying lmao
:P
